// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_addinformation.cpp"
#include "EWIEGA46WW/moc_addstudent.cpp"
#include "EWIEGA46WW/moc_addvariant.cpp"
#include "EWIEGA46WW/moc_create.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "EWIEGA46WW/moc_populate.cpp"
